### ISSUE TITLE
Main menu items will come to no-reaction after keyboard removed physically with Lenovo IdeaPad Duet

### ISSUE THREAD

**Issue by Setsu00** [google/jscin#27] opened 2020-09-03 00:46 UTC
Dear Sir,
very appreciate for this works which let me can input with Traditional BoPoMoFo with my Lenovo IdeaPad Duet.
Basically this project works great without much trouble.
But after some test I found that when I select JsCIN as current input method then remove the keyboard cover of my IdeaPad Duet, some operation with touch seem been locked or influenced and not able to interact with.
I have a short video for this symptom:

  https://drive.google.com/file/d/1zkwBD6xnVMTLBuR0Yyhr-BuVj6Xq07wF/view?usp=sharing

The symptom can be solved by re-connect the keyboard then switch to other input method, then again remove keyboard the problem will be solved. I assume there is something strange when physical keyboard removed.

Please have a check about this symptom. Will be glad to hear any solution.

**Comment by hungte** [comment] 2024-10-16 12:24
Thank yo for reporting this issue. Unfortunately the JSCIN has nothing to do with it, and I think it's probably the keyboard & input service backend (which provides the IME extension  API that JSCIN was based on) that has this issue and there's no easy way to fix. My suggestion would be to verify this with another extension based IME and see if that can be reproduced. If yes, file a bug to the ChromeOS input team.

**Comment by hungte** [comment] 2024-12-16 14:24
Closing here since it's a cros issue instead of jscin.

**Closed by hungte** 2024-12-16 14:24 UTC
